# Generated by Django 5.0 on 2023-12-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="contact",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
