# Generated by Django 5.0 on 2023-12-28 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="post_image",
        ),
    ]
