# Generated by Django 5.0 on 2023-12-29 22:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_alter_post_post_owner_comment_notification_reply"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reply",
            options={"ordering": ["-date_replied"], "verbose_name_plural": "Replies"},
        ),
    ]
