# Generated by Django 5.0 on 2024-01-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0006_rename_context_notification_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
