# Generated by Django 5.0 on 2024-01-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0007_post_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="like",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
