# Generated by Django 5.0 on 2024-01-01 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0008_alter_post_like"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="like",
        ),
        migrations.AddField(
            model_name="post",
            name="like",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
