# Generated by Django 5.0 on 2024-01-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0009_remove_post_like_post_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(),
        ),
    ]
